### ISSUE TITLE
Simplify entrypoint

### ISSUE THREAD

**Issue by nnadeau** [cicirello/Chips-n-Salsa#2]
When getting started with the repo, the two primary entrypoints are "building the code" and "running examples". 

While a java developer will have no problem building with `ant` and understanding why the `-cp` flag is needed to run the examples, these are an extra impedance for someone new to the repo. 

I'd recommend using a `Makefile` as the entrypoint. See https://github.com/cicirello/Chips-n-Salsa/pull/1 for an example. The READMEs will need to be updated as well.

Moreover, the two READMEs (README.md and examples/README.md) cite the same way to run the examples. This duplication of instructions can lead to future stale or out-of-sync documentation. Using a Makefile separates the implementation from the documentation.

cc https://github.com/openjournals/joss-reviews/issues/2448

**Comment by cicirello** [comment]
@nnadeau I merged your makefile, and then edited the two READMEs (see the referenced commits) to remove the redundancy.  How does it look now?

**Comment by nnadeau** [comment]
@cicirello 
- with a `Makefile`, a user should just need to call `make examples` to run all examples. This avoids:

>  Just replace org.cicirello.examples.chipsnsalsa.BitVectorExample in the above with the example program of your [..]

- Modern software development calls for protecting your master branch and using Pull Requests (PR) for all changes. The issue will then be closed by the PR. You can protect master by going to `https://github.com/nnadeau/Chips-n-Salsa/settings/branches` and add master as a protected branch

![image](https://user-images.githubusercontent.com/6395915/87698079-fa660800-c760-11ea-8438-e0ba16b34efb.png)
