### ISSUE TITLE
Set up automated testing and CI/CD

### ISSUE THREAD

**Issue by nnadeau** [cicirello/Chips-n-Salsa#4]
Good software practice calls for automated testing, continuous integrations, and continuous deployments. Each pull request, change, merge, and release should be rigorously tested and deployed without human intervention (the source of all errors).

Set up testing/CI/CD with one of the many free services, such as GitHub Actions, CircleCI, TravisCI, etc

cc https://github.com/openjournals/joss-reviews/issues/2448

**Comment by cicirello** [comment]
Set up testing/CI with GitHub Actions, in commit 9293c6a9076828314ea046641ba8df013c575b70
